name    'meltwater-swagger'
version '0.2.0'
source 'http://swagger.wordnik.com'
author 'meltwater'
license 'Apache License, Version 2.0'
summary 'Puppet Module for Swagger UI'
description 'Puppet Module for Swagger UI'
project_page 'https://github.com/meltwater/puppet-swagger'

dependency 'puppetlabs/stdlib', '>= 2.2.0'
dependency 'camptocamp-archive'
